// Generated by https://quicktype.io

export interface ModVersion {
    id:             string;
    project_id:     string;
    author_id:      string;
    featured:       boolean;
    name:           string;
    version_number: string;
    changelog:      string;
    changelog_url:  null;
    date_published: string;
    downloads:      number;
    version_type:   VersionType;
    files:          File[];
    dependencies:   any[];
    game_versions:  string[];
    loaders:        Loader[];
}

export enum AuthorID {
    DzLrfrbK = "DzLrfrbK",
    TEZXhE2U = "TEZXhE2U",
}

export interface File {
    hashes:   Hashes;
    url:      string;
    filename: string;
    primary:  boolean;
    size:     number;
}

export interface Hashes {
    sha512: string;
    sha1:   string;
}

export enum Loader {
    Fabric = "fabric",
}


export enum VersionType {
    Alpha = "alpha",
    Release = "release",
}
